# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/GameSetChat',
                'doc_host': 'https://lukexyz.github.io',
                'git_url': 'https://github.com/lukexyz/GameSetChat',
                'lib_path': 'GameSetChat'},
  'syms': {'GameSetChat.core': {'GameSetChat.core.foo': ('core.html#foo', 'GameSetChat/core.py')}}}
